version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: marketcart-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketcart_dev
      POSTGRES_USER: marketcart_user
      POSTGRES_PASSWORD: marketcart_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - marketcart-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketcart_user -d marketcart_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service (Development)
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    container_name: marketcart-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://marketcart_user:marketcart_password@postgres:5432/marketcart_dev
      PORT: 4000
      JWT_SECRET: dev-jwt-secret-key
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - marketcart-dev-network
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend Next.js Service (Development)
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    container_name: marketcart-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - marketcart-dev-network
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  marketcart-dev-network:
    driver: bridge
